---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - image: boranx/demo-api:latest
        imagePullPolicy: Always
        name: demo-api
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
spec:
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    app: demo-api