apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gdgcloud
  namespace: default
spec:
  secretName: gdgcloud-crt
  commonName: boran.fun
  dnsNames:
  - boran.fun
  - test.boran.fun
  - demo.boran.fun
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - boran.fun
      - test.boran.fun
      - demo.boran.fun